### ISSUE TITLE
Android Bote

### ISSUE THREAD

**Issue by sadsouler** [i2p/i2p.i2p-bote#106]
net.i2p.client.I2PSessionException: [I2P-Bote]: Cannot connect to the router on [Domain socket connection]:0
	at net.i2p.client.I2PSessionImpl.connect(I2PSessionImpl.java:559)
	at i2p.bote.I2PBote.initializeSession(I2PBote.java:296)
	at i2p.bote.I2PBote.access$600(I2PBote.java:129)
	at i2p.bote.I2PBote$ConnectTask.run(I2PBote.java:971)
Caused by:

java.io.IOException: Connection refused
	at android.net.LocalSocketImpl.connectLocal(Native Method)
	at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:292)
	at android.net.LocalSocket.connect(LocalSocket.java:145)
	at net.i2p.client.DomainSocket.<init>(DomainSocket.java:34)
	at net.i2p.client.DomainSocketFactory.createSocket(DomainSocketFactory.java:24)
	at net.i2p.client.I2PSessionImpl.connect(I2PSessionImpl.java:491)
	at i2p.bote.I2PBote.initializeSession(I2PBote.java:296)
	at i2p.bote.I2PBote.access$600(I2PBote.java:129)
	at i2p.bote.I2PBote$ConnectTask.run(I2PBote.java:971)

**Comment by str4d** [comment]
I'm hoping that this was fixed by #109, but I have not yet tested it to confirm.

**Comment by str4d** [comment]
0.6.1 has now been released. @sadsouler could you please test and confirm that the issue is fixed for you? A warning: any emails you had from a previous version will be lost when uninstalling the app in order to install 0.6.1, so if you have any and need them preserved, you will need to forward them to another I2P-Bote address before uninstalling.
