### ISSUE TITLE
Excessive logging by I2P-Bote (Trac #696)

### ISSUE THREAD

**Issue by str4d** [i2p/i2p.i2p-bote#11]
Historiques du routeur (configuration)
Emplacement du fichier: C:\Program Files\I2P\PortableApps\i2p\i2p\.\logs\log-router-1.txt

    18/08/12 14:40:58 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.
         java.net.NoRouteToHostException: Connection timed out
         at net.i2p.client.streaming.I2PSocketManagerFull.connect(I2PSocketManagerFull.java:252)
         at net.i2p.client.streaming.I2PSocketManagerFull.connect(I2PSocketManagerFull.java:271)
         at i2p.bote.network.I2PSendQueue.sendStream(I2PSendQueue.java:284)
         at i2p.bote.network.I2PSendQueue.send(I2PSendQueue.java:254)
         at i2p.bote.network.I2PSendQueue.doStep(I2PSendQueue.java:207)
         at i2p.bote.service.I2PBoteThread.run(I2PBoteThread.java:77)
    18/08/12 14:40:51 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.
         net.i2p.client.I2PSessionException: Already closed
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:196)
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:175)
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:128)
         at i2p.bote.network.I2PSendQueue.run(I2PSendQueue.java:225)
    18/08/12 14:39:50 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.
    18/08/12 14:37:50 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.
         net.i2p.client.I2PSessionException: Already closed
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:196)
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:175)
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:128)
         at i2p.bote.network.I2PSendQueue.run(I2PSendQueue.java:225)
    18/08/12 14:37:49 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.
    18/08/12 14:36:54 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.
    18/08/12 14:35:48 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.
         net.i2p.client.I2PSessionException: Already closed
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:196)
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:175)
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:128)
         at i2p.bote.network.I2PSendQueue.run(I2PSendQueue.java:225)
    18/08/12 14:35:48 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.
    18/08/12 14:33:47 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.
         net.i2p.client.I2PSessionException: Already closed
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:196)
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:175)
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:128)
         at i2p.bote.network.I2PSendQueue.run(I2PSendQueue.java:225)
    18/08/12 14:33:47 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.
    18/08/12 14:32:32 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.
         java.net.NoRouteToHostException: Connection timed out
         at net.i2p.client.streaming.I2PSocketManagerFull.connect(I2PSocketManagerFull.java:252)
         at net.i2p.client.streaming.I2PSocketManagerFull.connect(I2PSocketManagerFull.java:271)
         at i2p.bote.network.I2PSendQueue.sendStream(I2PSendQueue.java:284)
         at i2p.bote.network.I2PSendQueue.send(I2PSendQueue.java:254)
         at i2p.bote.network.I2PSendQueue.doStep(I2PSendQueue.java:207)
         at i2p.bote.service.I2PBoteThread.run(I2PBoteThread.java:77)
    18/08/12 14:31:47 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.
         net.i2p.client.I2PSessionException: Already closed
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:196)
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:175)
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:128)
         at i2p.bote.network.I2PSendQueue.run(I2PSendQueue.java:225)
    18/08/12 14:31:47 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.
    18/08/12 14:30:54 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.
    18/08/12 14:29:46 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.
         net.i2p.client.I2PSessionException: Already closed
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:196)
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:175)
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:128)
         at i2p.bote.network.I2PSendQueue.run(I2PSendQueue.java:225)
    18/08/12 14:28:46 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.
    18/08/12 14:26:45 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.
         net.i2p.client.I2PSessionException: Already closed
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:196)
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:175)
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:128)
         at i2p.bote.network.I2PSendQueue.run(I2PSendQueue.java:225)
    18/08/12 14:26:45 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.
    18/08/12 14:25:54 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.
    18/08/12 14:24:44 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.
         net.i2p.client.I2PSessionException: Already closed
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:196)
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:175)
         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:128)
         at i2p.bote.network.I2PSendQueue.run(I2PSendQueue.java:225)

Migrated from https://trac.i2p2.de/ticket/696
```json
{
    "status": "closed", 
    "changetime": "2012-08-19T23:32:53", 
    "description": "Historiques du routeur (configuration)\nEmplacement du fichier: C:\\Program Files\\I2P\\PortableApps\\i2p\\i2p\\.\\logs\\log-router-1.txt\n\n    18/08/12 14:40:58 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.\n         java.net.NoRouteToHostException: Connection timed out\n         at net.i2p.client.streaming.I2PSocketManagerFull.connect(I2PSocketManagerFull.java:252)\n         at net.i2p.client.streaming.I2PSocketManagerFull.connect(I2PSocketManagerFull.java:271)\n         at i2p.bote.network.I2PSendQueue.sendStream(I2PSendQueue.java:284)\n         at i2p.bote.network.I2PSendQueue.send(I2PSendQueue.java:254)\n         at i2p.bote.network.I2PSendQueue.doStep(I2PSendQueue.java:207)\n         at i2p.bote.service.I2PBoteThread.run(I2PBoteThread.java:77)\n    18/08/12 14:40:51 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.\n         net.i2p.client.I2PSessionException: Already closed\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:196)\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:175)\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:128)\n         at i2p.bote.network.I2PSendQueue.run(I2PSendQueue.java:225)\n    18/08/12 14:39:50 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.\n    18/08/12 14:37:50 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.\n         net.i2p.client.I2PSessionException: Already closed\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:196)\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:175)\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:128)\n         at i2p.bote.network.I2PSendQueue.run(I2PSendQueue.java:225)\n    18/08/12 14:37:49 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.\n    18/08/12 14:36:54 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.\n    18/08/12 14:35:48 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.\n         net.i2p.client.I2PSessionException: Already closed\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:196)\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:175)\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:128)\n         at i2p.bote.network.I2PSendQueue.run(I2PSendQueue.java:225)\n    18/08/12 14:35:48 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.\n    18/08/12 14:33:47 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.\n         net.i2p.client.I2PSessionException: Already closed\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:196)\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:175)\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:128)\n         at i2p.bote.network.I2PSendQueue.run(I2PSendQueue.java:225)\n    18/08/12 14:33:47 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.\n    18/08/12 14:32:32 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.\n         java.net.NoRouteToHostException: Connection timed out\n         at net.i2p.client.streaming.I2PSocketManagerFull.connect(I2PSocketManagerFull.java:252)\n         at net.i2p.client.streaming.I2PSocketManagerFull.connect(I2PSocketManagerFull.java:271)\n         at i2p.bote.network.I2PSendQueue.sendStream(I2PSendQueue.java:284)\n         at i2p.bote.network.I2PSendQueue.send(I2PSendQueue.java:254)\n         at i2p.bote.network.I2PSendQueue.doStep(I2PSendQueue.java:207)\n         at i2p.bote.service.I2PBoteThread.run(I2PBoteThread.java:77)\n    18/08/12 14:31:47 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.\n         net.i2p.client.I2PSessionException: Already closed\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:196)\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:175)\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:128)\n         at i2p.bote.network.I2PSendQueue.run(I2PSendQueue.java:225)\n    18/08/12 14:31:47 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.\n    18/08/12 14:30:54 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.\n    18/08/12 14:29:46 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.\n         net.i2p.client.I2PSessionException: Already closed\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:196)\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:175)\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:128)\n         at i2p.bote.network.I2PSendQueue.run(I2PSendQueue.java:225)\n    18/08/12 14:28:46 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.\n    18/08/12 14:26:45 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.\n         net.i2p.client.I2PSessionException: Already closed\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:196)\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:175)\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:128)\n         at i2p.bote.network.I2PSendQueue.run(I2PSendQueue.java:225)\n    18/08/12 14:26:45 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.\n    18/08/12 14:25:54 ERROR [Kademlia ] ademlia.ClosestNodesLookupTask: Lookup for closest nodes timed out.\n    18/08/12 14:24:44 ERROR [I2PSendQueue] i2p.bote.network.I2PSendQueue : Can't send packet.\n         net.i2p.client.I2PSessionException: Already closed\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:196)\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:175)\n         at net.i2p.client.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:128)\n         at i2p.bote.network.I2PSendQueue.run(I2PSendQueue.java:225)\n", 
    "reporter": "guest3113", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1345419173000000", 
    "component": "apps/plugins", 
    "summary": "Excessive logging by I2P-Bote", 
    "priority": "minor", 
    "keywords": "I2P-Bote", 
    "version": "0.9.1", 
    "time": "2012-08-18T12:59:34", 
    "milestone": "0.9.2", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by str4d** [comment]
Trac update at 20120818T13:04:54: 
* killyourtv commented:

> This "log spam" was fixed in the [http://plugins.i2p/plugins/i2pbote/ MTN build of I2P-Bote].


* killyourtv changed component from "unspecified" to "apps/plugins"
* killyourtv changed keywords from "" to "I2P-Bote"
* killyourtv changed priority from "major" to "minor"
* killyourtv changed resolution from "" to "fixed"
* killyourtv changed status from "new" to "closed"

**Comment by str4d** [comment]
Trac update at 20120819T23:32:53: killyourtv changed summary from "Bug 18/08/2012" to "Excessive logging by I2P-Bote"
