### ISSUE TITLE
download from bote.i2p, index.jsp missing 404

### ISSUE THREAD

**Issue by jacobsandersen** [i2p/i2p.i2p-bote#121]
downloaded fresh from bote.i2p, securemail icons are added but 404s immediately. index.jsp is missing?

i2p v0.9.41-0-1ubuntu1

https://puu.sh/DXODm/89817fc0ab.png

**Comment by bobdschingis** [comment]
Can you please look into you log directory (var/log/i2p) and poste the error lines. Maybe i got the same error as i tried to use i2pbote with the java router console. There has to be three files: log-router-0.txt log-router-1.txt and wrapper.log
In my situation it was related to a problem with tomcat. But i also didn't get it to work.

maybe it can help the maintainer to track the issue.

br

**Comment by bonedaddy** [comment]
Also getting an error, these are my logs:


```
va.io.FileNotFoundException: JAR entry WEB-INF/lib/tomcat-el-api-8.5.40.jar!/ not found in /home/solidity/.i2p/plugins/i2pbote/console/webapps/i2pbote.war
        at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:147)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:92)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.getTlds(MetaInfConfiguration.java:438)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanForTlds(MetaInfConfiguration.java:355)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanJars(MetaInfConfiguration.java:173)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.preConfigure(MetaInfConfiguration.java:107)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:506)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:544)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at net.i2p.router.web.WebAppStarter.startWebApp(WebAppStarter.java:71)
        at net.i2p.router.web.PluginStarter.startPlugin(PluginStarter.java:478)
        at net.i2p.router.web.PluginStarter.startPlugins(PluginStarter.java:267)
        at net.i2p.router.web.PluginStarter.run(PluginStarter.java:127)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at net.i2p.util.I2PThread.run(I2PThread.java:103)
```

**Comment by TheGreatestJannet** [comment]
Exact same issue here with the same error message as @postables. Any progress on this issue or a workaround?

**Comment by ghost** [comment]
I had this same issue. Just don't use the distro packaged i2p (even if from the official I2P repo). 

Instead use the Java installer from https://geti2p.net/en/download#unix .
**Remember:** disable and stop the i2p service before doing anything else!

After following the instructions from the website, install bote normally from http://bote.i2p/install/ .

**Note:** I2P won't autostart when you login, you have to add it to the autostart config manually.

**Comment by rootkea** [comment]
I2P Version: `0.9.42-0-1~disco+1`
OS: Debian Buster
log:
```
19/09/19, 12:51:43 PM WARN  [luginStarter] rg.eclipse.jetty.server.Server: Failed startup of context o.e.j.w.WebAppContext@31f15383{/i2pbote,jar:file:///var/lib/i2p/i2p-config/plugins/i2pbote/console/webapps/i2pbote.war!/,UNAVAILABLE}{/i2pbote.war}: java.io.FileNotFoundException: JAR entry WEB-INF/lib/tomcat-el-api-8.5.40.jar!/ not found in /var/lib/i2p/i2p-config/plugins/i2pbote/console/webapps/i2pbote.war
19/09/19, 12:51:43 PM ERROR [luginStarter] t.i2p.router.web.PluginStarter: Error resolving '/var/lib/i2p/i2p-config/plugins/i2pbote/console/webapps/i2pbote.war' in '/var/lib/i2p/i2p-config/plugins/i2pbote/console/webapps
java.io.FileNotFoundException: JAR entry WEB-INF/lib/tomcat-el-api-8.5.40.jar!/ not found in /var/lib/i2p/i2p-config/plugins/i2pbote/console/webapps/i2pbote.war
        at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:147)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:92)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.getTlds(MetaInfConfiguration.java:438)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanForTlds(MetaInfConfiguration.java:355)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanJars(MetaInfConfiguration.java:173)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.preConfigure(MetaInfConfiguration.java:107)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:506)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:544)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at net.i2p.router.web.WebAppStarter.startWebApp(WebAppStarter.java:71)
        at net.i2p.router.web.PluginStarter.startPlugin(PluginStarter.java:478)
        at net.i2p.router.web.PluginStarter.startPlugins(PluginStarter.java:267)
        at net.i2p.router.web.PluginStarter.run(PluginStarter.java:127)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at net.i2p.util.I2PThread.run(I2PThread.java:103)
```

**Comment by NetworkJack2** [comment]
Get the same issue on Arch, latest version of I2P:

pacman -Q i2p
i2p 0.9.43-2


from: log-router-0.txt

java.net.MalformedURLException: Nested JAR URLs are not supported
