### ISSUE TITLE
3 Bote errors:ConcurrentExecutionException,TooSmallPackets (Trac #1287)

### ISSUE THREAD

**Issue by str4d** [i2p/i2p.i2p-bote#20]
3 errors:
- about unability to check for update (maybe this should only be logged if it happens repeatedly, not if eepproxy fails once or eepsite down. for the future it could even be thought about a p2p update where instrad of checking the eepsite, other bote nodes arequeried and only updates signed by a signer on a configurable list of trusted signers are accepted)

- CEE

- dunno how those too small packets come about, maybe it's during shutdown? Is it save to simply rm them? will they be redownloaded, or a packet once downloaded is deleted for good? I know received mails are deleted, but not sure it's on a per-packet basis or only once the mail is complete AND correctly assembled. Anyhow, bote should recover from that on its own

```text
    20.05.14 23:39:41 ERROR [UpdateCheckr] i2p.bote.service.UpdateChecker: Can't check update URL: http://tjgidoycrw6s3guetge3kvrvynppqjmvqsosmtbmgqasa6vmsf6a.b32.i2p/i2pbote-update.xpi2p
    20.05.14 21:38:29 ERROR [UpdateCheckr] i2p.bote.service.UpdateChecker: Can't check update URL: http://tjgidoycrw6s3guetge3kvrvynppqjmvqsosmtbmgqasa6vmsf6a.b32.i2p/i2pbote-update.xpi2p
    20.05.14 20:38:09 ERROR [UpdateCheckr] i2p.bote.service.UpdateChecker: Can't check update URL: http://tjgidoycrw6s3guetge3kvrvynppqjmvqsosmtbmgqasa6vmsf6a.b32.i2p/i2pbote-update.xpi2p
    20.05.14 19:29:21 ERROR [onsole Jetty] i2p.bote.service.EmailChecker : Error while checking whether new mail has arrived.
         java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
         at java.util.concurrent.FutureTask.report(Unknown Source)
         at java.util.concurrent.FutureTask.get(Unknown Source)
         at i2p.bote.service.EmailChecker.newMailReceived(EmailChecker.java:158)
         at i2p.bote.I2PBote.newMailReceived(I2PBote.java:555)
         at i2p.bote.util.GeneralHelper.isNewMailReceived(GeneralHelper.java:315)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
         at java.lang.reflect.Method.invoke(Unknown Source)
         at javax.el.BeanELResolver.getValue(BeanELResolver.java:83)
         at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:54)
         at org.apache.el.parser.AstValue.getValue(AstValue.java:123)
         at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:186)
         at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:938)
         at i2p.bote.jsp.buttonFrame_jsp._jspx_meth_c_005fif_005f8(buttonFrame_jsp.java:824)
         at i2p.bote.jsp.buttonFrame_jsp._jspx_meth_c_005fif_005f4(buttonFrame_jsp.java:423)
         at i2p.bote.jsp.buttonFrame_jsp._jspService(buttonFrame_jsp.java:115)
         at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
         at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
         at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)
         at i2p.bote.web.CharsetFilter.doFilter(CharsetFilter.java:38)
         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
         at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
         at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
         at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
         at org.eclipse.jetty.server.Server.handle(Server.java:370)
         at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
         at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
         at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
         at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
         at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
         at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
         at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
         at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
         at java.lang.Thread.run(Unknown Source)
         Caused by: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
         at java.util.concurrent.FutureTask.report(Unknown Source)
         at java.util.concurrent.FutureTask.get(Unknown Source)
         at i2p.bote.network.CheckEmailTask.call(CheckEmailTask.java:131)
         at i2p.bote.network.CheckEmailTask.call(CheckEmailTask.java:61)
         at java.util.concurrent.FutureTask.run(Unknown Source)
         ... 3 more
         Caused by: java.util.ConcurrentModificationException
         at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
         at java.util.ArrayList$Itr.next(Unknown Source)
         at i2p.bote.network.kademlia.BucketManager.getAllUnlockedPeers(BucketManager.java:267)
         at i2p.bote.network.kademlia.ClosestNodesLookupTask.call(ClosestNodesLookupTask.java:106)
         at i2p.bote.network.kademlia.KademliaDHT.getClosestNodes(KademliaDHT.java:178)
         at i2p.bote.network.kademlia.KademliaDHT.find(KademliaDHT.java:261)
         at i2p.bote.network.kademlia.KademliaDHT.findAll(KademliaDHT.java:188)
         at i2p.bote.network.CheckEmailTask$EmailPacketTask.run(CheckEmailTask.java:201)
         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
         ... 4 more
    20.05.14 18:26:24 ERROR [ExpiratnThrd] i2p.bote.folder.Folder : Can't create a FolderElement from file: C:\ProgramData\Application Data\i2p\i2pbote\dht_email_pkt\pko46K5LXBn0-91y4A2a62mhvPsgDNOlTDtU4b~CGyQ=.pkt (file size=8192)
         i2p.bote.packet.MalformedPacketException: Can't instantiate packet for type code <E>
         at i2p.bote.packet.DataPacket.createPacket(DataPacket.java:104)
         at i2p.bote.packet.I2PBotePacket.createPacket(I2PBotePacket.java:118)
         at i2p.bote.packet.I2PBotePacket.createPacket(I2PBotePacket.java:90)
         at i2p.bote.folder.PacketFolder.createFolderElement(PacketFolder.java:85)
         at i2p.bote.folder.PacketFolder.createFolderElement(PacketFolder.java:42)
         at i2p.bote.folder.Folder$3.findNextElement(Folder.java:169)
         at i2p.bote.folder.Folder$3.next(Folder.java:150)
         at i2p.bote.folder.PacketFolder$1.next(PacketFolder.java:106)
         at i2p.bote.folder.PacketFolder$1.next(PacketFolder.java:90)
         at i2p.bote.folder.EmailPacketFolder.deleteExpired(EmailPacketFolder.java:143)
         at i2p.bote.service.ExpirationThread.run(ExpirationThread.java:53)
         Caused by: java.lang.reflect.InvocationTargetException
         at sun.reflect.GeneratedConstructorAccessor8.newInstance(Unknown Source)
         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
         at java.lang.reflect.Constructor.newInstance(Unknown Source)
         at i2p.bote.packet.DataPacket.createPacket(DataPacket.java:101)
         ... 10 more
         Caused by: java.nio.BufferUnderflowException
         at java.nio.HeapByteBuffer.get(Unknown Source)
         at java.nio.ByteBuffer.get(Unknown Source)
         at i2p.bote.packet.dht.EncryptedEmailPacket.<init>(EncryptedEmailPacket.java:102)
         ... 14 more

```

Migrated from https://trac.i2p2.de/ticket/1287
```json
{
    "status": "closed", 
    "changetime": "2016-01-25T20:00:40", 
    "description": "3 errors:\n- about unability to check for update (maybe this should only be logged if it happens repeatedly, not if eepproxy fails once or eepsite down. for the future it could even be thought about a p2p update where instrad of checking the eepsite, other bote nodes arequeried and only updates signed by a signer on a configurable list of trusted signers are accepted)\n\n- CEE\n\n- dunno how those too small packets come about, maybe it's during shutdown? Is it save to simply rm them? will they be redownloaded, or a packet once downloaded is deleted for good? I know received mails are deleted, but not sure it's on a per-packet basis or only once the mail is complete AND correctly assembled. Anyhow, bote should recover from that on its own\n\n{{{\n    20.05.14 23:39:41 ERROR [UpdateCheckr] i2p.bote.service.UpdateChecker: Can't check update URL: http://tjgidoycrw6s3guetge3kvrvynppqjmvqsosmtbmgqasa6vmsf6a.b32.i2p/i2pbote-update.xpi2p\n    20.05.14 21:38:29 ERROR [UpdateCheckr] i2p.bote.service.UpdateChecker: Can't check update URL: http://tjgidoycrw6s3guetge3kvrvynppqjmvqsosmtbmgqasa6vmsf6a.b32.i2p/i2pbote-update.xpi2p\n    20.05.14 20:38:09 ERROR [UpdateCheckr] i2p.bote.service.UpdateChecker: Can't check update URL: http://tjgidoycrw6s3guetge3kvrvynppqjmvqsosmtbmgqasa6vmsf6a.b32.i2p/i2pbote-update.xpi2p\n    20.05.14 19:29:21 ERROR [onsole Jetty] i2p.bote.service.EmailChecker : Error while checking whether new mail has arrived.\n         java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException\n         at java.util.concurrent.FutureTask.report(Unknown Source)\n         at java.util.concurrent.FutureTask.get(Unknown Source)\n         at i2p.bote.service.EmailChecker.newMailReceived(EmailChecker.java:158)\n         at i2p.bote.I2PBote.newMailReceived(I2PBote.java:555)\n         at i2p.bote.util.GeneralHelper.isNewMailReceived(GeneralHelper.java:315)\n         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\n         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\n         at java.lang.reflect.Method.invoke(Unknown Source)\n         at javax.el.BeanELResolver.getValue(BeanELResolver.java:83)\n         at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:54)\n         at org.apache.el.parser.AstValue.getValue(AstValue.java:123)\n         at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:186)\n         at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:938)\n         at i2p.bote.jsp.buttonFrame_jsp._jspx_meth_c_005fif_005f8(buttonFrame_jsp.java:824)\n         at i2p.bote.jsp.buttonFrame_jsp._jspx_meth_c_005fif_005f4(buttonFrame_jsp.java:423)\n         at i2p.bote.jsp.buttonFrame_jsp._jspService(buttonFrame_jsp.java:115)\n         at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)\n         at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)\n         at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)\n         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)\n         at i2p.bote.web.CharsetFilter.doFilter(CharsetFilter.java:38)\n         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)\n         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)\n         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)\n         at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)\n         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)\n         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)\n         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)\n         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)\n         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)\n         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)\n         at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)\n         at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)\n         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)\n         at org.eclipse.jetty.server.Server.handle(Server.java:370)\n         at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)\n         at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)\n         at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)\n         at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)\n         at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)\n         at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)\n         at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)\n         at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)\n         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n         at java.lang.Thread.run(Unknown Source)\n         Caused by: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException\n         at java.util.concurrent.FutureTask.report(Unknown Source)\n         at java.util.concurrent.FutureTask.get(Unknown Source)\n         at i2p.bote.network.CheckEmailTask.call(CheckEmailTask.java:131)\n         at i2p.bote.network.CheckEmailTask.call(CheckEmailTask.java:61)\n         at java.util.concurrent.FutureTask.run(Unknown Source)\n         ... 3 more\n         Caused by: java.util.ConcurrentModificationException\n         at java.util.ArrayList$Itr.checkForComodification(Unknown Source)\n         at java.util.ArrayList$Itr.next(Unknown Source)\n         at i2p.bote.network.kademlia.BucketManager.getAllUnlockedPeers(BucketManager.java:267)\n         at i2p.bote.network.kademlia.ClosestNodesLookupTask.call(ClosestNodesLookupTask.java:106)\n         at i2p.bote.network.kademlia.KademliaDHT.getClosestNodes(KademliaDHT.java:178)\n         at i2p.bote.network.kademlia.KademliaDHT.find(KademliaDHT.java:261)\n         at i2p.bote.network.kademlia.KademliaDHT.findAll(KademliaDHT.java:188)\n         at i2p.bote.network.CheckEmailTask$EmailPacketTask.run(CheckEmailTask.java:201)\n         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)\n         ... 4 more\n    20.05.14 18:26:24 ERROR [ExpiratnThrd] i2p.bote.folder.Folder : Can't create a FolderElement from file: C:\\ProgramData\\Application Data\\i2p\\i2pbote\\dht_email_pkt\\pko46K5LXBn0-91y4A2a62mhvPsgDNOlTDtU4b~CGyQ=.pkt (file size=8192)\n         i2p.bote.packet.MalformedPacketException: Can't instantiate packet for type code <E>\n         at i2p.bote.packet.DataPacket.createPacket(DataPacket.java:104)\n         at i2p.bote.packet.I2PBotePacket.createPacket(I2PBotePacket.java:118)\n         at i2p.bote.packet.I2PBotePacket.createPacket(I2PBotePacket.java:90)\n         at i2p.bote.folder.PacketFolder.createFolderElement(PacketFolder.java:85)\n         at i2p.bote.folder.PacketFolder.createFolderElement(PacketFolder.java:42)\n         at i2p.bote.folder.Folder$3.findNextElement(Folder.java:169)\n         at i2p.bote.folder.Folder$3.next(Folder.java:150)\n         at i2p.bote.folder.PacketFolder$1.next(PacketFolder.java:106)\n         at i2p.bote.folder.PacketFolder$1.next(PacketFolder.java:90)\n         at i2p.bote.folder.EmailPacketFolder.deleteExpired(EmailPacketFolder.java:143)\n         at i2p.bote.service.ExpirationThread.run(ExpirationThread.java:53)\n         Caused by: java.lang.reflect.InvocationTargetException\n         at sun.reflect.GeneratedConstructorAccessor8.newInstance(Unknown Source)\n         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)\n         at java.lang.reflect.Constructor.newInstance(Unknown Source)\n         at i2p.bote.packet.DataPacket.createPacket(DataPacket.java:101)\n         ... 10 more\n         Caused by: java.nio.BufferUnderflowException\n         at java.nio.HeapByteBuffer.get(Unknown Source)\n         at java.nio.ByteBuffer.get(Unknown Source)\n         at i2p.bote.packet.dht.EncryptedEmailPacket.<init>(EncryptedEmailPacket.java:102)\n         ... 14 more\n\n}}}", 
    "reporter": "user", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1453752040717604", 
    "component": "apps/plugins", 
    "summary": "3 Bote errors:ConcurrentExecutionException,TooSmallPackets", 
    "priority": "minor", 
    "keywords": "I2P-Bote", 
    "version": "0.9.12", 
    "parents": "", 
    "time": "2014-05-20T22:41:04", 
    "milestone": "0.9.21", 
    "owner": "str4d", 
    "type": "defect"
}
```

**Comment by str4d** [comment]
Trac update at 20140825T20:55:34: 
* str4d changed _comment0 from:

> Update checker has been dropped from trunk by HungryHobo (it was there before I2P did automatic plugin update checks).
> 
> Looking into the other errors.

to:

> 1409021118130126


* str4d commented:

> Update checker has been dropped from trunk by !HungryHobo (it was there before I2P did automatic plugin update checks).
> 
> Looking into the other errors.


* str4d changed keywords from "bote, packets" to "I2P-Bote, packets"
* str4d changed milestone from "0.9.14" to ""
* str4d changed owner from "HungryHobo" to "str4d"
* str4d changed status from "new" to "accepted"

**Comment by str4d** [comment]
Trac update at 20150110T04:11:12: str4d changed keywords from "I2P-Bote, packets" to "I2P-Bote race"

**Comment by str4d** [comment]
Trac update at 20150721T10:12:57: 
* str4d changed _comment0 from:

> 'ConcurrentModificationException' duplicated in #1586, fixed there.
> 
> Still looking into the `BufferUnderflowException`.

to:

> 1437473594388339


* str4d commented:

> `ConcurrentModificationException` duplicated in #52, fixed there.
> 
> Still looking into the `BufferUnderflowException`.


* str4d changed keywords from "I2P-Bote race" to "I2P-Bote"

**Comment by str4d** [comment]
Trac update at 20150722T01:30:56: 
* str4d commented:

> The `MalformedPacketException` error above is exactly that, an error when trying to read a packet from file. Generally this is unrecoverable. These fall into two categories:
> 
> * DHT packets that are being stored by I2P-Bote for another user (the case in the error logs above)
> * Incomplete email packets that have been successfully decrypted after downloading from a remote user, but either the packet inside was originally corrupt, or the unencrypted packet is later corrupted on-disk.
> 
> DHT packets can be safely deleted because we can assume that the packet was either corrupted during network transfer to us (but has been safely stored with another I2P-Bote node), or was corrupt from the beginning and shouldn't be stored at all.
> 
> Incomplete email packets, I'm not sure about. In most cases, emails are compressed prior to being split into packets, so if one of the packets is corrupted locally then the email is unrecoverable (because packets are deleted from the DHT as soon as they are fetched). But is there a case for potentially recovering some email data? Right now, nothing is ever deleted from the incomplete folder unless a full email has been formed, but this should probably be changed to deleting unused incomplete packets after 100 days (when the missing packets will have definitely been deleted from the DHT). Or possibly even sooner? Research is needed into the origin of these packets (whether from incomplete downloads, or packets from old emails being downloaded later from servers that didn't get the deletion request).
> 
> For now, I will delete malformed DHT packets, and leave the existing error for incomplete email packets.


* str4d changed milestone from "" to "0.9.21"

**Comment by str4d** [comment]
Trac update at 20150722T11:46:32: 
* str4d commented:

> Malformed DHT packets deleted in `3838fb2d792f8ff033b3dc5b94713f854f43538b`.


* str4d changed status from "accepted" to "testing"

**Comment by str4d** [comment]
Trac update at 20160125T20:00:40: 
* str4d commented:

> No further comments, so closing this (incomplete email packets will be handled separately later).


* str4d changed resolution from "" to "fixed"
* str4d changed status from "testing" to "closed"
