### ISSUE TITLE
I2P-Bote ConcurrentModificationException (Trac #1586)

### ISSUE THREAD

**Issue by str4d** [i2p/i2p.i2p-bote#52]
I2P running since 15 hours. I did not have this issue before using 0.9.19-31 (I used 0.9.19-30 before).

I2P version: 0.9.19-31-rc
Java version: Oracle Corporation 1.7.0_79 (OpenJDK Runtime Environment 1.7.0_79-b14)
Wrapper version: 3.5.25
Server version: 8.1.17.v20150415
Servlet version: Jasper JSP 2.1 Engine
Platform: Linux amd64 3.13.0-37-generic
Jbigi: Locally optimized library libjbigi-linux-athlon64_64.so loaded from file
Encoding: UTF-8
Charset: UTF-8

28/05/15 15:55:39 ERROR [e Jetty-2157] i2p.bote.service.EmailChecker : Error while checking whether new mail has arrived.
     java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
     at java.util.concurrent.FutureTask.report(FutureTask.java:122)
     at java.util.concurrent.FutureTask.get(FutureTask.java:202)
     at i2p.bote.service.EmailChecker.newMailReceived(EmailChecker.java:158)
     at i2p.bote.I2PBote.newMailReceived(I2PBote.java:566)
     at i2p.bote.util.GeneralHelper.isNewMailReceived(GeneralHelper.java:330)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:606)
     at javax.el.BeanELResolver.getValue(BeanELResolver.java:83)
     at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:54)
     at org.apache.el.parser.AstValue.getValue(AstValue.java:123)
     at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:182)
     at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:919)
     at i2p.bote.jsp.buttonFrame_jsp._jspx_meth_c_005fif_005f8(buttonFrame_jsp.java:824)
     at i2p.bote.jsp.buttonFrame_jsp._jspx_meth_c_005fif_005f4(buttonFrame_jsp.java:423)
     at i2p.bote.jsp.buttonFrame_jsp._jspService(buttonFrame_jsp.java:115)
     at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)
     at i2p.bote.web.CharsetFilter.doFilter(CharsetFilter.java:38)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
     at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
     at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
     at org.eclipse.jetty.server.Server.handle(Server.java:370)
     at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
     at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
     at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
     at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
     at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
     at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
     at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
     at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
     at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
     at java.lang.Thread.run(Thread.java:745)
     Caused by: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
     at java.util.concurrent.FutureTask.report(FutureTask.java:122)
     at java.util.concurrent.FutureTask.get(FutureTask.java:202)
     at i2p.bote.network.CheckEmailTask.call(CheckEmailTask.java:131)
     at i2p.bote.network.CheckEmailTask.call(CheckEmailTask.java:61)
     at java.util.concurrent.FutureTask.run(FutureTask.java:262)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     ... 1 more
     Caused by: java.util.ConcurrentModificationException
     at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
     at java.util.ArrayList$Itr.next(ArrayList.java:831)
     at i2p.bote.network.kademlia.BucketManager.getAllUnlockedPeers(BucketManager.java:267)
     at i2p.bote.network.kademlia.ClosestNodesLookupTask.call(ClosestNodesLookupTask.java:106)
     at i2p.bote.network.kademlia.KademliaDHT.getClosestNodes(KademliaDHT.java:179)
     at i2p.bote.network.kademlia.KademliaDHT.find(KademliaDHT.java:262)
     at i2p.bote.network.kademlia.KademliaDHT.findAll(KademliaDHT.java:189)
     at i2p.bote.network.CheckEmailTask$EmailPacketTask.run(CheckEmailTask.java:201)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
     ... 4 more
28/05/15 05:10:39 ERROR [UpdateCheckr] i2p.bote.service.UpdateChecker: Can't check update URL: http://tjgidoycrw6s3guetge3kvrvynppqjmvqsosmtbmgqasa6vmsf6a.b32.i2p/i2pbote-update.xpi2p

Migrated from https://trac.i2p2.de/ticket/1586
```json
{
    "status": "closed", 
    "changetime": "2016-11-27T02:27:01", 
    "description": "I2P running since 15 hours. I did not have this issue before using 0.9.19-31 (I used 0.9.19-30 before).\n\nI2P version: 0.9.19-31-rc\nJava version: Oracle Corporation 1.7.0_79 (OpenJDK Runtime Environment 1.7.0_79-b14)\nWrapper version: 3.5.25\nServer version: 8.1.17.v20150415\nServlet version: Jasper JSP 2.1 Engine\nPlatform: Linux amd64 3.13.0-37-generic\nJbigi: Locally optimized library libjbigi-linux-athlon64_64.so loaded from file\nEncoding: UTF-8\nCharset: UTF-8\n\n28/05/15 15:55:39 ERROR [e Jetty-2157] i2p.bote.service.EmailChecker : Error while checking whether new mail has arrived.\n     java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException\n     at java.util.concurrent.FutureTask.report(FutureTask.java:122)\n     at java.util.concurrent.FutureTask.get(FutureTask.java:202)\n     at i2p.bote.service.EmailChecker.newMailReceived(EmailChecker.java:158)\n     at i2p.bote.I2PBote.newMailReceived(I2PBote.java:566)\n     at i2p.bote.util.GeneralHelper.isNewMailReceived(GeneralHelper.java:330)\n     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\n     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n     at java.lang.reflect.Method.invoke(Method.java:606)\n     at javax.el.BeanELResolver.getValue(BeanELResolver.java:83)\n     at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:54)\n     at org.apache.el.parser.AstValue.getValue(AstValue.java:123)\n     at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:182)\n     at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:919)\n     at i2p.bote.jsp.buttonFrame_jsp._jspx_meth_c_005fif_005f8(buttonFrame_jsp.java:824)\n     at i2p.bote.jsp.buttonFrame_jsp._jspx_meth_c_005fif_005f4(buttonFrame_jsp.java:423)\n     at i2p.bote.jsp.buttonFrame_jsp._jspService(buttonFrame_jsp.java:115)\n     at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)\n     at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)\n     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)\n     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)\n     at i2p.bote.web.CharsetFilter.doFilter(CharsetFilter.java:38)\n     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)\n     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)\n     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)\n     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)\n     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)\n     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)\n     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)\n     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)\n     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)\n     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)\n     at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)\n     at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)\n     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)\n     at org.eclipse.jetty.server.Server.handle(Server.java:370)\n     at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)\n     at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)\n     at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)\n     at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)\n     at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)\n     at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)\n     at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)\n     at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)\n     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)\n     at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)\n     at java.lang.Thread.run(Thread.java:745)\n     Caused by: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException\n     at java.util.concurrent.FutureTask.report(FutureTask.java:122)\n     at java.util.concurrent.FutureTask.get(FutureTask.java:202)\n     at i2p.bote.network.CheckEmailTask.call(CheckEmailTask.java:131)\n     at i2p.bote.network.CheckEmailTask.call(CheckEmailTask.java:61)\n     at java.util.concurrent.FutureTask.run(FutureTask.java:262)\n     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\n     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)\n     ... 1 more\n     Caused by: java.util.ConcurrentModificationException\n     at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)\n     at java.util.ArrayList$Itr.next(ArrayList.java:831)\n     at i2p.bote.network.kademlia.BucketManager.getAllUnlockedPeers(BucketManager.java:267)\n     at i2p.bote.network.kademlia.ClosestNodesLookupTask.call(ClosestNodesLookupTask.java:106)\n     at i2p.bote.network.kademlia.KademliaDHT.getClosestNodes(KademliaDHT.java:179)\n     at i2p.bote.network.kademlia.KademliaDHT.find(KademliaDHT.java:262)\n     at i2p.bote.network.kademlia.KademliaDHT.findAll(KademliaDHT.java:189)\n     at i2p.bote.network.CheckEmailTask$EmailPacketTask.run(CheckEmailTask.java:201)\n     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)\n     ... 4 more\n28/05/15 05:10:39 ERROR [UpdateCheckr] i2p.bote.service.UpdateChecker: Can't check update URL: http://tjgidoycrw6s3guetge3kvrvynppqjmvqsosmtbmgqasa6vmsf6a.b32.i2p/i2pbote-update.xpi2p\n", 
    "reporter": "hummingbird", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1480213621974567", 
    "component": "apps/other", 
    "summary": "I2P-Bote ConcurrentModificationException", 
    "priority": "minor", 
    "keywords": "I2P-Bote", 
    "version": "0.9.19", 
    "parents": "", 
    "time": "2015-05-28T14:41:39", 
    "milestone": "0.9.21", 
    "owner": "HungryHobo", 
    "type": "defect"
}
```

**Comment by str4d** [comment]
Trac update at 20150608T18:19:26: 
* hummingbird changed owner from "" to "HungryHobo"
* hummingbird changed status from "new" to "assigned"

**Comment by str4d** [comment]
Trac update at 20150721T10:10:31: 
* str4d changed _comment0 from:

> Update checker has been dropped from trunk by HungryHobo (it was there before I2P did automatic plugin update checks).
> 
> `ConcurrentModificationException` fixed in `50f06182e970d4eb7d371f6c5bf157f63c00a636`.

to:

> 1437473462389464


* str4d commented:

> Update checker has been dropped from trunk by !HungryHobo (it was there before I2P did automatic plugin update checks).
> 
> `ConcurrentModificationException` fixed in `50f06182e970d4eb7d371f6c5bf157f63c00a636`.


* str4d changed milestone from "undecided" to "0.9.21"
* str4d changed status from "assigned" to "testing"

**Comment by str4d** [comment]
Trac update at 20150723T02:05:46: str4d changed summary from "Issue in I2P-Bote" to "I2P-Bote ConcurrentModificationException"

**Comment by str4d** [comment]
Trac update at 20161127T02:27:01: 
* str4d commented:

> No further reports, optimistically closing.


* str4d changed resolution from "" to "fixed"
* str4d changed status from "testing" to "closed"
