### ISSUE TITLE
I2P-Bote NPE (Trac #1597)

### ISSUE THREAD

**Issue by str4d** [i2p/i2p.i2p-bote#53]
I2P 0.9.20
OpenJDK 1.7.0_79-b14

```text
6/7/15 6:28:36 PM ERROR [ConnectTask ] i2p.bote.I2PBote : Can't initialize the application.
     java.lang.NullPointerException
     at i2p.bote.I2PBote.initializeSession(I2PBote.java:294)
     at i2p.bote.I2PBote.access$600(I2PBote.java:127)
     at i2p.bote.I2PBote$ConnectTask.run(I2PBote.java:954)
6/7/15 6:28:36 PM ERROR [ConnectTask ] i2p.bote.I2PBote : Error creating I2PSocketManagerFactory
6/7/15 6:28:36 PM ERROR [ConnectTask ] eaming.I2PSocketManagerFactory: Error creating session for socket manager
     net.i2p.client.I2PSessionException: [I2P-Bote https://trac.i2p2.de/ticket/23179]: Cannot connect to the router on [internal connection]:0
     at net.i2p.client.I2PSessionImpl.connect(I2PSessionImpl.java:559)
     at net.i2p.client.streaming.I2PSocketManagerFactory.createManager(I2PSocketManagerFactory.java:244)
     at net.i2p.client.streaming.I2PSocketManagerFactory.createManager(I2PSocketManagerFactory.java:166)
     at net.i2p.client.streaming.I2PSocketManagerFactory.createManager(I2PSocketManagerFactory.java:145)
     at i2p.bote.I2PBote.initializeSession(I2PBote.java:282)
     at i2p.bote.I2PBote.access$600(I2PBote.java:127)
     at i2p.bote.I2PBote$ConnectTask.run(I2PBote.java:954)
     Caused by: java.io.IOException: No tunnels built after waiting 5 minutes. Your network connection may be down, or there is severe network congestion.
     at net.i2p.client.I2PSessionImpl.connect(I2PSessionImpl.java:536)
     ... 6 more
```

Migrated from https://trac.i2p2.de/ticket/1597
```json
{
    "status": "closed", 
    "changetime": "2015-07-22T21:28:37", 
    "description": "I2P 0.9.20\nOpenJDK 1.7.0_79-b14\n\n\n{{{\n6/7/15 6:28:36 PM ERROR [ConnectTask ] i2p.bote.I2PBote : Can't initialize the application.\n     java.lang.NullPointerException\n     at i2p.bote.I2PBote.initializeSession(I2PBote.java:294)\n     at i2p.bote.I2PBote.access$600(I2PBote.java:127)\n     at i2p.bote.I2PBote$ConnectTask.run(I2PBote.java:954)\n6/7/15 6:28:36 PM ERROR [ConnectTask ] i2p.bote.I2PBote : Error creating I2PSocketManagerFactory\n6/7/15 6:28:36 PM ERROR [ConnectTask ] eaming.I2PSocketManagerFactory: Error creating session for socket manager\n     net.i2p.client.I2PSessionException: [I2P-Bote #23179]: Cannot connect to the router on [internal connection]:0\n     at net.i2p.client.I2PSessionImpl.connect(I2PSessionImpl.java:559)\n     at net.i2p.client.streaming.I2PSocketManagerFactory.createManager(I2PSocketManagerFactory.java:244)\n     at net.i2p.client.streaming.I2PSocketManagerFactory.createManager(I2PSocketManagerFactory.java:166)\n     at net.i2p.client.streaming.I2PSocketManagerFactory.createManager(I2PSocketManagerFactory.java:145)\n     at i2p.bote.I2PBote.initializeSession(I2PBote.java:282)\n     at i2p.bote.I2PBote.access$600(I2PBote.java:127)\n     at i2p.bote.I2PBote$ConnectTask.run(I2PBote.java:954)\n     Caused by: java.io.IOException: No tunnels built after waiting 5 minutes. Your network connection may be down, or there is severe network congestion.\n     at net.i2p.client.I2PSessionImpl.connect(I2PSessionImpl.java:536)\n     ... 6 more\n}}}", 
    "reporter": "killyourtv", 
    "cc": "str4d", 
    "resolution": "fixed", 
    "_ts": "1437600517605132", 
    "component": "apps/plugins", 
    "summary": "I2P-Bote NPE", 
    "priority": "minor", 
    "keywords": "I2P-Bote", 
    "version": "0.9.20", 
    "parents": "", 
    "time": "2015-06-07T19:49:26", 
    "milestone": "0.9.21", 
    "owner": "HungryHobo", 
    "type": "defect"
}
```

**Comment by str4d** [comment]
Trac update at 20150722T21:28:37: 
* str4d commented:

> This was fixed 7 months ago in `455772b2a5e9f7ed13bdd6bb883d2a471092627f`, but the last I2P-Bote plugin release was a year ago, hence why this is still visible. A better error will be thrown after the next plugin release.


* str4d changed milestone from "undecided" to "0.9.21"
* str4d changed resolution from "" to "fixed"
* str4d changed status from "new" to "closed"
