### ISSUE TITLE
Bote fails to start at first run after update (Trac #1630)

### ISSUE THREAD

**Issue by str4d** [i2p/i2p.i2p-bote#56]
Migrated from https://trac.i2p2.de/ticket/1630
```json
{
    "status": "assigned", 
    "changetime": "2017-01-15T13:56:07", 
    "description": "After the update to 0.9.21, i2p-bote did not start.\nLooking into the logs I see:\n\n\nI2P version: 0.9.21-0-1ubuntu1\nJava version: Oracle Corporation 1.7.0_79 (OpenJDK Runtime Environment 1.7.0_79-b14)\nWrapper version: 3.5.25\nServer version: 8.1.17.v20150415\nServlet version: Jasper JSP 2.1 Engine\nPlatform: Linux amd64 3.13.0-39-lowlatency\nProcessor: Core 2 (Conroe) (core2)\nJbigi: Locally optimized native BigInteger library loaded from file\nEncoding: UTF-8\nCharset: UTF-8\n\n ERROR[luginStarter] t.i2p.router.web.PluginStarter: Failed to start plugin: i2pbote\n     java.lang.IllegalArgumentException: Bad temp directory: /tmp/i2p-daemon/i2p-cFkskYum.tmp/jetty-work-i2pbote72985129\n     at org.eclipse.jetty.webapp.WebAppContext.setTempDirectory(WebAppContext.java:1119)\n     at net.i2p.router.web.WebAppStarter.addWebApp(WebAppStarter.java:101)\n     at net.i2p.router.web.WebAppStarter.startWebApp(WebAppStarter.java:57)\n     at net.i2p.router.web.PluginStarter.startPlugin(PluginStarter.java:380)\n     at net.i2p.router.web.PluginStarter.startPlugins(PluginStarter.java:211)\n     at net.i2p.router.web.PluginStarter.run(PluginStarter.java:87)\n     at java.lang.Thread.run(Thread.java:745)\n     at net.i2p.util.I2PThread.run(I2PThread.java:115)\n\n\nTrying to start it manually, gives the following error in the web console:\njava.lang.IllegalArgumentException: Bad temp directory: /tmp/i2p-daemon/i2p-cFkskYum.tmp/jetty-work-i2pbote776606184\n\n\nI had that error before and then it was fixed by a router restart.\nI don't remember well, but maybe last time I had it, it was also right after router update\nSince this is the second time it occurrs it might be a bug with i2p and not just my computer being in the mood for getting on my nerves.\n\nI ran -22-rc before and it started fine.\n\nAlso this time, a simple router restart fixed it.\n", 
    "reporter": "user", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1484488567605384", 
    "component": "apps/plugins", 
    "summary": "Bote fails to start at first run after update", 
    "priority": "maintenance", 
    "keywords": "I2P-Bote", 
    "version": "0.9.21", 
    "parents": "", 
    "time": "2015-08-01T22:28:59", 
    "milestone": "0.9.22", 
    "owner": "str4d", 
    "type": "defect"
}
```

**Comment by str4d** [comment]
Trac update at 20150803T12:46:46: 
* killyourtv changed component from "apps/plugins" to "package/debian"
* killyourtv changed milestone from "undecided" to "0.9.22"
* killyourtv changed owner from "" to "killyourtv"
* killyourtv changed status from "new" to "accepted"

**Comment by str4d** [comment]
Trac update at 20150803T12:48:40: killyourtv commented:

> May be apparmor related. (My rules may need some relaxing)

**Comment by str4d** [comment]
Trac update at 20150804T14:12:31: user commented:

> But I have selected no, as reply to the AppArmor question in dpkg-reconfigure i2p…

**Comment by str4d** [comment]
Trac update at 20170115T13:56:07: 
* zzz changed component from "package/debian" to "apps/plugins"
* zzz changed owner from "killyourtv" to "str4d"
* zzz changed status from "accepted" to "assigned"
