### ISSUE TITLE
Bote v0.4: Error while checking whether new mail has arrived. (Trac #1643)

### ISSUE THREAD

**Issue by str4d** [i2p/i2p.i2p-bote#59]
Bote v0.4 just installed. I2P 

I2P version: 0.9.21-0
Java version: Oracle Corporation 1.7.0_79 (OpenJDK Runtime Environment 1.7.0_79-b14)
Wrapper version: 3.5.25
Server version: 8.1.17.v20150415
Servlet version: Jasper JSP 2.1 Engine
Platform: Linux amd64 3.16.0-38-generic
Jbigi: Locally optimized library libjbigi-linux-athlon64_64.so loaded from file
Encoding: UTF-8
Charset: UTF-8

I2P Router Logs 

21/08/15 08:36:07 ↓↓↓ 1 similar message omitted ↓↓↓
21/08/15 08:27:09 ERROR [e Jetty-2690] i2p.bote.service.EmailChecker : Error while checking whether new mail has arrived.
     java.util.ConcurrentModificationException
     at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
     at java.util.HashMap$EntryIterator.next(HashMap.java:962)
     at java.util.HashMap$EntryIterator.next(HashMap.java:960)
     at i2p.bote.service.EmailChecker.updatePendingTasks(EmailChecker.java:196)
     at i2p.bote.service.EmailChecker.isCheckingForMail(EmailChecker.java:151)
     at i2p.bote.I2PBote.isCheckingForMail(I2PBote.java:541)
     at i2p.bote.util.GeneralHelper.isCheckingForMail(GeneralHelper.java:324)
     at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:606)
     at javax.el.BeanELResolver.getValue(BeanELResolver.java:83)
     at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:54)
     at org.apache.el.parser.AstValue.getValue(AstValue.java:123)
     at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:182)
     at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:897)
     at i2p.bote.jsp.buttonFrame_jsp._jspx_meth_c_005fif_005f1(buttonFrame_jsp.java:267)
     at i2p.bote.jsp.buttonFrame_jsp._jspService(buttonFrame_jsp.java:103)
     at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)
     at i2p.bote.web.CharsetFilter.doFilter(CharsetFilter.java:38)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)
     at net.i2p.servlet.filters.XSSFilter.doFilter(XSSFilter.java:28)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
     at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
     at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
     at org.eclipse.jetty.server.Server.handle(Server.java:370)
     at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
     at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
     at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
     at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
     at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
     at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
     at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
     at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
     at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
     at java.lang.Thread.run(Thread.java:745)

Migrated from https://trac.i2p2.de/ticket/1643
```json
{
    "status": "closed", 
    "changetime": "2015-09-13T00:42:06", 
    "description": "Bote v0.4 just installed. I2P \n\nI2P version: 0.9.21-0\nJava version: Oracle Corporation 1.7.0_79 (OpenJDK Runtime Environment 1.7.0_79-b14)\nWrapper version: 3.5.25\nServer version: 8.1.17.v20150415\nServlet version: Jasper JSP 2.1 Engine\nPlatform: Linux amd64 3.16.0-38-generic\nJbigi: Locally optimized library libjbigi-linux-athlon64_64.so loaded from file\nEncoding: UTF-8\nCharset: UTF-8\n\nI2P Router Logs \n\n21/08/15 08:36:07 \u2193\u2193\u2193 1 similar message omitted \u2193\u2193\u2193\n21/08/15 08:27:09 ERROR [e Jetty-2690] i2p.bote.service.EmailChecker : Error while checking whether new mail has arrived.\n     java.util.ConcurrentModificationException\n     at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)\n     at java.util.HashMap$EntryIterator.next(HashMap.java:962)\n     at java.util.HashMap$EntryIterator.next(HashMap.java:960)\n     at i2p.bote.service.EmailChecker.updatePendingTasks(EmailChecker.java:196)\n     at i2p.bote.service.EmailChecker.isCheckingForMail(EmailChecker.java:151)\n     at i2p.bote.I2PBote.isCheckingForMail(I2PBote.java:541)\n     at i2p.bote.util.GeneralHelper.isCheckingForMail(GeneralHelper.java:324)\n     at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source)\n     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n     at java.lang.reflect.Method.invoke(Method.java:606)\n     at javax.el.BeanELResolver.getValue(BeanELResolver.java:83)\n     at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:54)\n     at org.apache.el.parser.AstValue.getValue(AstValue.java:123)\n     at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:182)\n     at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:897)\n     at i2p.bote.jsp.buttonFrame_jsp._jspx_meth_c_005fif_005f1(buttonFrame_jsp.java:267)\n     at i2p.bote.jsp.buttonFrame_jsp._jspService(buttonFrame_jsp.java:103)\n     at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)\n     at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)\n     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)\n     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)\n     at i2p.bote.web.CharsetFilter.doFilter(CharsetFilter.java:38)\n     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)\n     at net.i2p.servlet.filters.XSSFilter.doFilter(XSSFilter.java:28)\n     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)\n     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)\n     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)\n     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)\n     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)\n     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)\n     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)\n     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)\n     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)\n     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)\n     at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)\n     at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)\n     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)\n     at org.eclipse.jetty.server.Server.handle(Server.java:370)\n     at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)\n     at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)\n     at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)\n     at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)\n     at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)\n     at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)\n     at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)\n     at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)\n     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)\n     at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)\n     at java.lang.Thread.run(Thread.java:745)\n", 
    "reporter": "hummingbird", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1442104926402241", 
    "component": "apps/plugins", 
    "summary": "Bote v0.4: Error while checking whether new mail has arrived.", 
    "priority": "minor", 
    "keywords": "I2P-Bote", 
    "version": "0.9.21", 
    "parents": "", 
    "time": "2015-08-21T06:43:05", 
    "milestone": "n/a", 
    "owner": "str4d", 
    "type": "defect"
}
```

**Comment by str4d** [comment]
Trac update at 20150821T11:49:03: 
* str4d commented:

> Known bug, I discovered it 10 minutes after releasing 0.4. It's a stupid mistake I made in my fix of a blocking bug in 0.3. But it can be safely ignored - it only delays the visual completion of email checking by one page refresh.
> 
> Fixed in `39fefdfe33c57dad7d0950046a14d7af2b32902e`.


* str4d changed milestone from "undecided" to "n/a"
* str4d changed status from "new" to "testing"

**Comment by str4d** [comment]
Trac update at 20150822T19:46:02: zzz commented:

> see also #61 closed as dup

**Comment by str4d** [comment]
Trac update at 20150913T00:41:49: 
* str4d commented:

> 0.4.1 is out, and I'm not seeing constant error messages in the logs any more.


* str4d changed resolution from "" to "fixed"
* str4d changed status from "testing" to "closed"

**Comment by str4d** [comment]
Trac update at 20150913T00:42:06: str4d changed owner from "" to "str4d"
