### ISSUE TITLE
Bote v0.4: Error while checking whether new mail has arrived. (java.util.ConcurrentModificationException) (Trac #1645)

### ISSUE THREAD

**Issue by str4d** [i2p/i2p.i2p-bote#61]
Strange errors in my log, I didn't have this with previous Bote (v0.2.10). Bote GUI is OK but it seems to loop checking mails "Checking for mail...  Last checked: 02:23").

22/08/15 07:26:24 ↓↓↓ 1 similar message omitted ↓↓↓
22/08/15 07:25:24 ↓↓↓ 1 similar message omitted ↓↓↓
22/08/15 07:24:24 ↓↓↓ 1 similar message omitted ↓↓↓
22/08/15 07:23:24 ERROR [EmailChecker] i2p.bote.service.EmailChecker : Error while checking whether new mail has arrived.
     java.util.ConcurrentModificationException
     at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
     at java.util.HashMap$EntryIterator.next(HashMap.java:962)
     at java.util.HashMap$EntryIterator.next(HashMap.java:960)
     at i2p.bote.service.EmailChecker.updatePendingTasks(EmailChecker.java:196)
     at i2p.bote.service.EmailChecker.isCheckingForMail(EmailChecker.java:151)
     at i2p.bote.service.EmailChecker.checkForMail(EmailChecker.java:111)
     at i2p.bote.service.EmailChecker.run(EmailChecker.java:225)
22/08/15 04:22:24 ↓↓↓ 1 similar message omitted ↓↓↓
22/08/15 04:21:24 ↓↓↓ 1 similar message omitted ↓↓↓
22/08/15 04:20:24 ↓↓↓ 1 similar message omitted ↓↓↓
22/08/15 04:19:24 ERROR [EmailChecker] i2p.bote.service.EmailChecker : Error while checking whether new mail has arrived.
     java.util.ConcurrentModificationException
     at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
     at java.util.HashMap$EntryIterator.next(HashMap.java:962)
     at java.util.HashMap$EntryIterator.next(HashMap.java:960)
     at i2p.bote.service.EmailChecker.updatePendingTasks(EmailChecker.java:196)
     at i2p.bote.service.EmailChecker.isCheckingForMail(EmailChecker.java:151)
     at i2p.bote.service.EmailChecker.checkForMail(EmailChecker.java:111)
     at i2p.bote.service.EmailChecker.run(EmailChecker.java:225)
22/08/15 01:18:24 ↓↓↓ 1 similar message omitted ↓↓↓
22/08/15 01:17:24 ↓↓↓ 1 similar message omitted ↓↓↓
22/08/15 01:16:24 ERROR [EmailChecker] i2p.bote.service.EmailChecker : Error while checking whether new mail has arrived.
     java.util.ConcurrentModificationException
     at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
     at java.util.HashMap$EntryIterator.next(HashMap.java:962)
     at java.util.HashMap$EntryIterator.next(HashMap.java:960)
     at i2p.bote.service.EmailChecker.updatePendingTasks(EmailChecker.java:196)
     at i2p.bote.service.EmailChecker.isCheckingForMail(EmailChecker.java:151)
     at i2p.bote.service.EmailChecker.checkForMail(EmailChecker.java:111)
     at i2p.bote.service.EmailChecker.run(EmailChecker.java:225)
21/08/15 22:30:26 ERROR [le Jetty-873] i2p.bote.service.EmailChecker : Error while checking whether new mail has arrived.
     java.util.ConcurrentModificationException
     at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
     at java.util.HashMap$EntryIterator.next(HashMap.java:962)
     at java.util.HashMap$EntryIterator.next(HashMap.java:960)
     at i2p.bote.service.EmailChecker.updatePendingTasks(EmailChecker.java:196)
     at i2p.bote.service.EmailChecker.isCheckingForMail(EmailChecker.java:151)
     at i2p.bote.I2PBote.isCheckingForMail(I2PBote.java:541)
     at i2p.bote.util.GeneralHelper.isCheckingForMail(GeneralHelper.java:324)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:606)
     at javax.el.BeanELResolver.getValue(BeanELResolver.java:83)
     at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:54)
     at org.apache.el.parser.AstValue.getValue(AstValue.java:123)
     at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:182)
     at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:897)
     at i2p.bote.jsp.buttonFrame_jsp._jspx_meth_c_005fif_005f1(buttonFrame_jsp.java:267)
     at i2p.bote.jsp.buttonFrame_jsp._jspService(buttonFrame_jsp.java:103)
     at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)
     at i2p.bote.web.CharsetFilter.doFilter(CharsetFilter.java:38)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)
     at net.i2p.servlet.filters.XSSFilter.doFilter(XSSFilter.java:28)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
     at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
     at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
     at org.eclipse.jetty.server.Server.handle(Server.java:370)
     at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
     at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
     at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
     at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
     at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
     at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
     at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
     at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
     at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
     at java.lang.Thread.run(Thread.java:745)
21/08/15 21:40:42 ↓↓↓ 3 similar messages omitted ↓↓↓
21/08/15 21:40:22 ERROR [le Jetty-527] i2p.bote.service.EmailChecker : Error while checking whether new mail has arrived.
     java.util.ConcurrentModificationException
     at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
     at java.util.HashMap$EntryIterator.next(HashMap.java:962)
     at java.util.HashMap$EntryIterator.next(HashMap.java:960)
     at i2p.bote.service.EmailChecker.updatePendingTasks(EmailChecker.java:196)
     at i2p.bote.service.EmailChecker.isCheckingForMail(EmailChecker.java:151)
     at i2p.bote.I2PBote.isCheckingForMail(I2PBote.java:541)
     at i2p.bote.util.GeneralHelper.isCheckingForMail(GeneralHelper.java:324)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:606)
     at javax.el.BeanELResolver.getValue(BeanELResolver.java:83)
     at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:54)
     at org.apache.el.parser.AstValue.getValue(AstValue.java:123)
     at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:182)
     at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:897)
     at i2p.bote.jsp.buttonFrame_jsp._jspx_meth_c_005fif_005f1(buttonFrame_jsp.java:267)
     at i2p.bote.jsp.buttonFrame_jsp._jspService(buttonFrame_jsp.java:103)
     at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)
     at i2p.bote.web.CharsetFilter.doFilter(CharsetFilter.java:38)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)
     at net.i2p.servlet.filters.XSSFilter.doFilter(XSSFilter.java:28)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
     at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
     at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
     at org.eclipse.jetty.server.Server.handle(Server.java:370)
     at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
     at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
     at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
     at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
     at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
     at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
     at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
     at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
     at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
     at java.lang.Thread.run(Thread.java:745)
21/08/15 21:20:45 INFO [JobQueue 3/4] b.kademlia.FloodfillMonitorJob: Only 664 ff peers and we want 5000 so we are becoming floodfill

Migrated from https://trac.i2p2.de/ticket/1645
```json
{
    "status": "closed", 
    "changetime": "2015-08-22T19:44:39", 
    "description": "Strange errors in my log, I didn't have this with previous Bote (v0.2.10). Bote GUI is OK but it seems to loop checking mails \"Checking for mail...  Last checked: 02:23\").\n\n22/08/15 07:26:24 \u2193\u2193\u2193 1 similar message omitted \u2193\u2193\u2193\n22/08/15 07:25:24 \u2193\u2193\u2193 1 similar message omitted \u2193\u2193\u2193\n22/08/15 07:24:24 \u2193\u2193\u2193 1 similar message omitted \u2193\u2193\u2193\n22/08/15 07:23:24 ERROR [EmailChecker] i2p.bote.service.EmailChecker : Error while checking whether new mail has arrived.\n     java.util.ConcurrentModificationException\n     at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)\n     at java.util.HashMap$EntryIterator.next(HashMap.java:962)\n     at java.util.HashMap$EntryIterator.next(HashMap.java:960)\n     at i2p.bote.service.EmailChecker.updatePendingTasks(EmailChecker.java:196)\n     at i2p.bote.service.EmailChecker.isCheckingForMail(EmailChecker.java:151)\n     at i2p.bote.service.EmailChecker.checkForMail(EmailChecker.java:111)\n     at i2p.bote.service.EmailChecker.run(EmailChecker.java:225)\n22/08/15 04:22:24 \u2193\u2193\u2193 1 similar message omitted \u2193\u2193\u2193\n22/08/15 04:21:24 \u2193\u2193\u2193 1 similar message omitted \u2193\u2193\u2193\n22/08/15 04:20:24 \u2193\u2193\u2193 1 similar message omitted \u2193\u2193\u2193\n22/08/15 04:19:24 ERROR [EmailChecker] i2p.bote.service.EmailChecker : Error while checking whether new mail has arrived.\n     java.util.ConcurrentModificationException\n     at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)\n     at java.util.HashMap$EntryIterator.next(HashMap.java:962)\n     at java.util.HashMap$EntryIterator.next(HashMap.java:960)\n     at i2p.bote.service.EmailChecker.updatePendingTasks(EmailChecker.java:196)\n     at i2p.bote.service.EmailChecker.isCheckingForMail(EmailChecker.java:151)\n     at i2p.bote.service.EmailChecker.checkForMail(EmailChecker.java:111)\n     at i2p.bote.service.EmailChecker.run(EmailChecker.java:225)\n22/08/15 01:18:24 \u2193\u2193\u2193 1 similar message omitted \u2193\u2193\u2193\n22/08/15 01:17:24 \u2193\u2193\u2193 1 similar message omitted \u2193\u2193\u2193\n22/08/15 01:16:24 ERROR [EmailChecker] i2p.bote.service.EmailChecker : Error while checking whether new mail has arrived.\n     java.util.ConcurrentModificationException\n     at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)\n     at java.util.HashMap$EntryIterator.next(HashMap.java:962)\n     at java.util.HashMap$EntryIterator.next(HashMap.java:960)\n     at i2p.bote.service.EmailChecker.updatePendingTasks(EmailChecker.java:196)\n     at i2p.bote.service.EmailChecker.isCheckingForMail(EmailChecker.java:151)\n     at i2p.bote.service.EmailChecker.checkForMail(EmailChecker.java:111)\n     at i2p.bote.service.EmailChecker.run(EmailChecker.java:225)\n21/08/15 22:30:26 ERROR [le Jetty-873] i2p.bote.service.EmailChecker : Error while checking whether new mail has arrived.\n     java.util.ConcurrentModificationException\n     at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)\n     at java.util.HashMap$EntryIterator.next(HashMap.java:962)\n     at java.util.HashMap$EntryIterator.next(HashMap.java:960)\n     at i2p.bote.service.EmailChecker.updatePendingTasks(EmailChecker.java:196)\n     at i2p.bote.service.EmailChecker.isCheckingForMail(EmailChecker.java:151)\n     at i2p.bote.I2PBote.isCheckingForMail(I2PBote.java:541)\n     at i2p.bote.util.GeneralHelper.isCheckingForMail(GeneralHelper.java:324)\n     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\n     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n     at java.lang.reflect.Method.invoke(Method.java:606)\n     at javax.el.BeanELResolver.getValue(BeanELResolver.java:83)\n     at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:54)\n     at org.apache.el.parser.AstValue.getValue(AstValue.java:123)\n     at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:182)\n     at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:897)\n     at i2p.bote.jsp.buttonFrame_jsp._jspx_meth_c_005fif_005f1(buttonFrame_jsp.java:267)\n     at i2p.bote.jsp.buttonFrame_jsp._jspService(buttonFrame_jsp.java:103)\n     at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)\n     at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)\n     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)\n     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)\n     at i2p.bote.web.CharsetFilter.doFilter(CharsetFilter.java:38)\n     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)\n     at net.i2p.servlet.filters.XSSFilter.doFilter(XSSFilter.java:28)\n     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)\n     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)\n     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)\n     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)\n     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)\n     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)\n     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)\n     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)\n     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)\n     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)\n     at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)\n     at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)\n     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)\n     at org.eclipse.jetty.server.Server.handle(Server.java:370)\n     at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)\n     at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)\n     at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)\n     at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)\n     at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)\n     at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)\n     at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)\n     at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)\n     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)\n     at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)\n     at java.lang.Thread.run(Thread.java:745)\n21/08/15 21:40:42 \u2193\u2193\u2193 3 similar messages omitted \u2193\u2193\u2193\n21/08/15 21:40:22 ERROR [le Jetty-527] i2p.bote.service.EmailChecker : Error while checking whether new mail has arrived.\n     java.util.ConcurrentModificationException\n     at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)\n     at java.util.HashMap$EntryIterator.next(HashMap.java:962)\n     at java.util.HashMap$EntryIterator.next(HashMap.java:960)\n     at i2p.bote.service.EmailChecker.updatePendingTasks(EmailChecker.java:196)\n     at i2p.bote.service.EmailChecker.isCheckingForMail(EmailChecker.java:151)\n     at i2p.bote.I2PBote.isCheckingForMail(I2PBote.java:541)\n     at i2p.bote.util.GeneralHelper.isCheckingForMail(GeneralHelper.java:324)\n     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\n     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n     at java.lang.reflect.Method.invoke(Method.java:606)\n     at javax.el.BeanELResolver.getValue(BeanELResolver.java:83)\n     at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:54)\n     at org.apache.el.parser.AstValue.getValue(AstValue.java:123)\n     at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:182)\n     at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:897)\n     at i2p.bote.jsp.buttonFrame_jsp._jspx_meth_c_005fif_005f1(buttonFrame_jsp.java:267)\n     at i2p.bote.jsp.buttonFrame_jsp._jspService(buttonFrame_jsp.java:103)\n     at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)\n     at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)\n     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)\n     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)\n     at i2p.bote.web.CharsetFilter.doFilter(CharsetFilter.java:38)\n     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)\n     at net.i2p.servlet.filters.XSSFilter.doFilter(XSSFilter.java:28)\n     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)\n     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)\n     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)\n     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)\n     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)\n     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)\n     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)\n     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)\n     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)\n     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)\n     at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)\n     at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)\n     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)\n     at org.eclipse.jetty.server.Server.handle(Server.java:370)\n     at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)\n     at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)\n     at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)\n     at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)\n     at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)\n     at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)\n     at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)\n     at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)\n     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)\n     at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)\n     at java.lang.Thread.run(Thread.java:745)\n21/08/15 21:20:45 INFO [JobQueue 3/4] b.kademlia.FloodfillMonitorJob: Only 664 ff peers and we want 5000 so we are becoming floodfill", 
    "reporter": "hummingbird", 
    "cc": "", 
    "resolution": "duplicate", 
    "_ts": "1440272679179538", 
    "component": "apps/plugins", 
    "summary": "Bote v0.4: Error while checking whether new mail has arrived. (java.util.ConcurrentModificationException)", 
    "priority": "minor", 
    "keywords": "I2P-Bote", 
    "version": "0.9.21", 
    "parents": "", 
    "time": "2015-08-22T05:52:47", 
    "milestone": "undecided", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by str4d** [comment]
Trac update at 20150822T19:44:39: 
* zzz commented:

> Dup of #59


* zzz changed resolution from "" to "duplicate"
* zzz changed status from "new" to "closed"
