### ISSUE TITLE
I2P-Bote concurrent.ExecutionException (Trac #1703)

### ISSUE THREAD

**Issue by str4d** [i2p/i2p.i2p-bote#70]
```text
I2P version: 0.9.22-21-deb1
Java version: Oracle Corporation 1.8.0_66-internal (OpenJDK Runtime Environment 1.8.0_66-internal-b17)
Wrapper version: 3.5.26
Server version: 8.1.17.v20150415
Servlet version: Jasper JSP 2.1 Engine
Platform: Linux amd64 4.2.0-1-amd64
Processor: Bulldozer FX-6100/8100 (athlon64)
Jbigi: Locally optimized native BigInteger library loaded from file
Encoding: UTF-8
Charset: UTF-8
```

```text
Version	0.4.1
Signed by	str4d@mail.i2p
Date	2015-09-12 15:46
Author	str4d@mail.i2p
```

```text
11/03/15 14:03:28.565 ERROR [EmailChecker] i2p.bote.service.EmailChecker : Error while checking whether new mail has arrived.
     java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
     at java.util.concurrent.FutureTask.report(FutureTask.java:122)
     at java.util.concurrent.FutureTask.get(FutureTask.java:206)
     at i2p.bote.service.EmailChecker.updatePendingTasks(EmailChecker.java:202)
     at i2p.bote.service.EmailChecker.isCheckingForMail(EmailChecker.java:152)
     at i2p.bote.service.EmailChecker.checkForMail(EmailChecker.java:112)
     at i2p.bote.service.EmailChecker.run(EmailChecker.java:230)
     Caused by: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
     at java.util.concurrent.FutureTask.report(FutureTask.java:122)
     at java.util.concurrent.FutureTask.get(FutureTask.java:206)
     at i2p.bote.network.CheckEmailTask.call(CheckEmailTask.java:131)
     at i2p.bote.network.CheckEmailTask.call(CheckEmailTask.java:61)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     at java.lang.Thread.run(Thread.java:745)
     Caused by: java.util.ConcurrentModificationException
     at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
     at java.util.ArrayList$Itr.next(ArrayList.java:851)
     at i2p.bote.network.kademlia.BucketManager.getAllUnlockedPeers(BucketManager.java:268)
     at i2p.bote.network.kademlia.ClosestNodesLookupTask.call(ClosestNodesLookupTask.java:107)
     at i2p.bote.network.kademlia.KademliaDHT.getClosestNodes(KademliaDHT.java:180)
     at i2p.bote.network.kademlia.KademliaDHT.find(KademliaDHT.java:263)
     at i2p.bote.network.kademlia.KademliaDHT.findAll(KademliaDHT.java:190)
     at i2p.bote.network.CheckEmailTask$EmailPacketTask.run(CheckEmailTask.java:201)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
     ... 4 more
```

Migrated from https://trac.i2p2.de/ticket/1703
```json
{
    "status": "closed", 
    "changetime": "2016-01-27T18:18:07", 
    "description": "{{{\nI2P version: 0.9.22-21-deb1\nJava version: Oracle Corporation 1.8.0_66-internal (OpenJDK Runtime Environment 1.8.0_66-internal-b17)\nWrapper version: 3.5.26\nServer version: 8.1.17.v20150415\nServlet version: Jasper JSP 2.1 Engine\nPlatform: Linux amd64 4.2.0-1-amd64\nProcessor: Bulldozer FX-6100/8100 (athlon64)\nJbigi: Locally optimized native BigInteger library loaded from file\nEncoding: UTF-8\nCharset: UTF-8\n}}}\n\n{{{\nVersion\t0.4.1\nSigned by\tstr4d@mail.i2p\nDate\t2015-09-12 15:46\nAuthor\tstr4d@mail.i2p\n}}}\n\n\n\n\n{{{\n11/03/15 14:03:28.565 ERROR [EmailChecker] i2p.bote.service.EmailChecker : Error while checking whether new mail has arrived.\n     java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException\n     at java.util.concurrent.FutureTask.report(FutureTask.java:122)\n     at java.util.concurrent.FutureTask.get(FutureTask.java:206)\n     at i2p.bote.service.EmailChecker.updatePendingTasks(EmailChecker.java:202)\n     at i2p.bote.service.EmailChecker.isCheckingForMail(EmailChecker.java:152)\n     at i2p.bote.service.EmailChecker.checkForMail(EmailChecker.java:112)\n     at i2p.bote.service.EmailChecker.run(EmailChecker.java:230)\n     Caused by: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException\n     at java.util.concurrent.FutureTask.report(FutureTask.java:122)\n     at java.util.concurrent.FutureTask.get(FutureTask.java:206)\n     at i2p.bote.network.CheckEmailTask.call(CheckEmailTask.java:131)\n     at i2p.bote.network.CheckEmailTask.call(CheckEmailTask.java:61)\n     at java.util.concurrent.FutureTask.run(FutureTask.java:266)\n     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n     at java.lang.Thread.run(Thread.java:745)\n     Caused by: java.util.ConcurrentModificationException\n     at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)\n     at java.util.ArrayList$Itr.next(ArrayList.java:851)\n     at i2p.bote.network.kademlia.BucketManager.getAllUnlockedPeers(BucketManager.java:268)\n     at i2p.bote.network.kademlia.ClosestNodesLookupTask.call(ClosestNodesLookupTask.java:107)\n     at i2p.bote.network.kademlia.KademliaDHT.getClosestNodes(KademliaDHT.java:180)\n     at i2p.bote.network.kademlia.KademliaDHT.find(KademliaDHT.java:263)\n     at i2p.bote.network.kademlia.KademliaDHT.findAll(KademliaDHT.java:190)\n     at i2p.bote.network.CheckEmailTask$EmailPacketTask.run(CheckEmailTask.java:201)\n     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n     ... 4 more\n}}}", 
    "reporter": "killyourtv", 
    "cc": "str4d", 
    "resolution": "fixed", 
    "_ts": "1453918687457716", 
    "component": "apps/plugins", 
    "summary": "I2P-Bote concurrent.ExecutionException", 
    "priority": "minor", 
    "keywords": "I2P-Bote", 
    "version": "0.9.22", 
    "parents": "", 
    "time": "2015-11-03T14:07:28", 
    "milestone": "0.9.23", 
    "owner": "str4d", 
    "type": "defect"
}
```

**Comment by str4d** [comment]
Trac update at 20151103T15:10:38: 
* zzz commented:

> On quick glance, the locking in BucketManager looks shaky. See also previously fixed #52 (or was it...)
> 
> May be desirable to someday migrate to common net.i2p.kademlia, although there may be features in HH's impl we need to backport first. Last I looked, his had some advantages. Also the whole SBucket thing... Anyway, just musing, irrelevant to this ticket.
> 


* zzz changed owner from "" to "str4d"
* zzz changed status from "new" to "assigned"
* zzz changed version from "" to "0.9.22"

**Comment by str4d** [comment]
Trac update at 20151103T22:12:21: kay commented:

> It seems (here and in the other ticket mentioned above) that
> BucketManager.getAllUnlockedPeers iterates over a bucket peer-list
> that gets changed during the iteration. The List of peers is
> a Collections.synchronizedList that mandates manual synchronization
> when iterating over it.  
> 
> I propose two solutions both concerning the AbstractBucket class:
> 
> 1) use CopyOnWriteArrayList for the peers' List, i.e.
> 
> ```text
>  import java.util.List;
> +import java.util.concurrent.CopyOnWriteArrayList;
>  
>  import net.i2p.data.Destination;
>  import net.i2p.data.Hash;
> @@ -46,7 +49,7 @@ abstract class AbstractBucket implements
>      protected int capacity;
>      
>      public AbstractBucket(int capacity) {
> -        peers = Collections.synchronizedList(new ArrayList<KademliaPeer>());
> +        peers = new CopyOnWriteArrayList<KademliaPeer>();
>          this.capacity = capacity;
>      }
> 
> ```
> 
> 2) return a copy-iterator, i.e. using i2p.bote.Util 
> 
> ```text
> @@ -109,5 +114,6 @@ abstract class AbstractBucket implements
>      @Override
>      public Iterator<KademliaPeer> iterator() {
> -        return peers.iterator();
> +        return Util.synchronizedCopy(peers).iterator();
>      }
> ```
> 
> Solution no. 1 seems better b/c the iterator would throw
> an UnsupportedOperationException for modification attempts,
> and thus fail fast.
> 
>

**Comment by str4d** [comment]
Trac update at 20151115T04:50:29: 
* str4d commented:

> I concur with solution 1, it's the same thing I did for BucketManager in #52.
> 
> Committed in `f9edfbef5dfd2aa7109ff5761992774a6a82c249`.


* str4d changed milestone from "undecided" to "0.9.23"
* str4d changed status from "assigned" to "testing"

**Comment by str4d** [comment]
Trac update at 20160127T18:18:07: 
* str4d commented:

> Haven't had any more reports after 0.4.2 release, assuming fixed.


* str4d changed resolution from "" to "fixed"
* str4d changed status from "testing" to "closed"
