### ISSUE TITLE
CheckEmailTask: Can't decrypt email packet (Trac #1714)

### ISSUE THREAD

**Issue by str4d** [i2p/i2p.i2p-bote#73]
Migrated from https://trac.i2p2.de/ticket/1714
```json
{
    "status": "infoneeded_new", 
    "changetime": "2015-11-24T07:43:04", 
    "description": "I'm seeing the following logged with I2P-Bote 0.4.2:\n\n{{{\n11/21/15 18:55:10.995 ERROR [EmailPktTask] 2p.bote.network.CheckEmailTask: Can't decrypt email packet: Type=EncryptedEmailPacket, code=<E>, sizeBytes=9755, DHTkey=[Hash: UszLYwdf6m0ms2Gxo6MikQ8ftepnHrhLM1h9MQiJNgQ=], tstamp=0, alg=521-bit Elliptic Curve Encryption, delVerifHash=[Hash: 1-s5v9nRwY0bwfByboloIDIxAsebqik8zW3ubIhwti0=], encrLen=9682\njavax.crypto.BadPaddingException: pad block corrupted\n        at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$BufferedGenericBlockCipher.doFinal(Unknown Source)\n        at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source)\n        at javax.crypto.Cipher.doFinal(Cipher.java:2377)\n        at i2p.bote.crypto.AbstractCryptoImplementation.decryptAes(AbstractCryptoImplementation.java:97)\n        at i2p.bote.crypto.ECDH_ECDSA.decrypt(ECDH_ECDSA.java:353)\n        at i2p.bote.packet.dht.EncryptedEmailPacket.decrypt(EncryptedEmailPacket.java:164)\n        at i2p.bote.network.CheckEmailTask$EmailPacketTask.run(CheckEmailTask.java:216)\n        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n        at java.util.concurrent.FutureTask.run(FutureTask.java:266)\n        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n        at java.lang.Thread.run(Thread.java:745)\n11/21/15 18:55:10.995 ERROR [EmailPktTask] 2p.bote.network.CheckEmailTask: Can't decrypt email packet: Type=EncryptedEmailPacket, code=<E>, sizeBytes=7067, DHTkey=[Hash: KW6I0PQiD~yAnZIkz~eTx0jd4jq0WjaBnbcPTg2NHGQ=], tstamp=0, alg=521-bit Elliptic Curve Encryption, delVerifHash=[Hash: R96~1Zyb2J~PCxjSag-7k2awKqH9w8tz3UiWAubr8TM=], encrLen=6994\njavax.crypto.BadPaddingException: pad block corrupted\n        at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$BufferedGenericBlockCipher.doFinal(Unknown Source)\n        at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source)\n        at javax.crypto.Cipher.doFinal(Cipher.java:2377)\n        at i2p.bote.crypto.AbstractCryptoImplementation.decryptAes(AbstractCryptoImplementation.java:97)\n        at i2p.bote.crypto.ECDH_ECDSA.decrypt(ECDH_ECDSA.java:353)\n        at i2p.bote.packet.dht.EncryptedEmailPacket.decrypt(EncryptedEmailPacket.java:164)\n        at i2p.bote.network.CheckEmailTask$EmailPacketTask.run(CheckEmailTask.java:216)\n        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n        at java.util.concurrent.FutureTask.run(FutureTask.java:266)\n        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n        at java.lang.Thread.run(Thread.java:745)\n\n}}}", 
    "reporter": "killyourtv", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1448350984442828", 
    "component": "apps/plugins", 
    "summary": "CheckEmailTask: Can't decrypt email packet", 
    "priority": "minor", 
    "keywords": "I2P-Bote", 
    "version": "0.9.23", 
    "parents": "", 
    "time": "2015-11-22T20:57:27", 
    "milestone": "undecided", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by str4d** [comment]
Trac update at 20151124T07:42:49: str4d commented:

> Not sure what is causing this, I don't see anything in the 0.4.2 update (yet) that could have caused this. Are you sure it never happened in earlier versions? ie. is this a noticeably common error in your logs now?

**Comment by str4d** [comment]
Trac update at 20151124T07:43:04: str4d changed status from "new" to "infoneeded_new"

**Comment by mppdidi** [comment]
i have seen this when files are attached - only appears on receiver side.

**Comment by mppdidi** [comment]
`ERROR [EmailPktTask] 2p.bote.network.CheckEmailTask: Can't decrypt email packet: Type=EncryptedEmailPacket, code=<E>, sizeBytes=9722, DHTkey=[Hash: xxxxx=], tstamp=0, alg=ECDH-256 / ECDSA-256, delVerifHash=[Hash: xxxx=], encrLen=9649
javax.crypto.BadPaddingException: pad block corrupted
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$BufferedGenericBlockCipher.doFinal(Unknown Source)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source)
	at javax.crypto.Cipher.doFinal(Cipher.java:2377)
	at i2p.bote.crypto.AbstractCryptoImplementation.decryptAes(AbstractCryptoImplementation.java:97)
	at i2p.bote.crypto.ECDH_ECDSA.decrypt(ECDH_ECDSA.java:353)
	at i2p.bote.packet.dht.EncryptedEmailPacket.decrypt(EncryptedEmailPacket.java:164)
	at i2p.bote.network.CheckEmailTask$EmailPacketTask.run(CheckEmailTask.java:216)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748`
