### ISSUE TITLE
Bote fails to connect to I2P Android

### ISSUE THREAD

**Issue by str4d** [i2p/i2p.i2p-bote#91]
Reported by @furyalex on https://github.com/i2p/i2p.i2p-bote.android (migrated here):

---

I installed latest versions of Bote and I2P router from Google play.

Router seems to be working. I can browse .i2p sites in Firefox. But when I press "connect to network" button in Bote it fails with

```
net.i2p.client.I2PSessionException: [I2P-Bote]: Cannot connect to the router on [Domain socket connection]:0
at net.i2p.client.I2PSessionImpl.connect(I2PSessionImpl.java:559)
at i2p.bote.I2PBote.initializeSession(I2PBote.java:296)
at i2p.bote.I2PBote.access$600(I2PBote.java:129)
at i2p.bote.I2PBote$ConnectTask.run(I2PBote.java:971)
Caused by:

java.io.IOException: Connection refused
at android.net.LocalSocketImpl.connectLocal(Native Method)
at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:290)
at android.net.LocalSocket.connect(LocalSocket.java:130)
at net.i2p.client.DomainSocket.(DomainSocket.java:34)
at net.i2p.client.DomainSocketFactory.createSocket(DomainSocketFactory.java:24)
at net.i2p.client.I2PSessionImpl.connect(I2PSessionImpl.java:491)
at i2p.bote.I2PBote.initializeSession(I2PBote.java:296)
at i2p.bote.I2PBote.access$600(I2PBote.java:129)
at i2p.bote.I2PBote$ConnectTask.run(I2PBote.java:971)
```

Could you please suggest how I can resolve this.

I'm on Android 6.0.1 from AT&T. G890AUCS4CPF3

**Comment by str4d** [comment]
Comment by @Orbixx:

> Experience the same.

**Comment by str4d** [comment]
AFAICT this was caused by an unintentional API change at some point in I2P Android, and the fact that the last Bote release was June 2015 🙁

I am working on a new release, which locally appears to connect fine to the latest I2P Android release.

**Comment by furyalex** [comment]
Hello,

Is there any progress in this? I still have this problem which makes Bote almost unusable. Same issue happens with latest versions on Samsung S9+ on Android 9 (G965U1UEU3CSA8)

**Comment by str4d** [comment]
0.6.1 has been released, which should address this problem. A warning: any emails you had from a previous version will be lost when uninstalling the app in order to install 0.6.1, so if you have any and need them preserved, you will need to forward them to another I2P-Bote address before uninstalling.
